### ISSUE TITLE
Bug in Google Collab version.

### ISSUE THREAD

**Issue by Axiom-Design** [FrozenBurning/Text2Light#1]
Hello, while trying to execute the last block of code from Google Collab, I'm given this error

```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-21-027de206138d>](https://localhost:8080/#) in <module>
     10 if opt.resume_global:
     11     if not os.path.exists(opt.resume_global):
---> 12         raise ValueError("Cannot find {}".format(opt.resume_global))
     13     print("Resuming from global sampler ckpt...")
     14     assert os.path.isdir(opt.resume_global), opt.resume_global

ValueError: Cannot find ./logs/text2light_released_model/global_sampler_clip/
```
All other code blocks seemed to have executed correctly, so I'm not entirely sure what the problem is.

***Edit***
Actually, it seems as though it didn't download all the files it needed to from Google Drive. Swapping over to the One Drive files seems to have fixed it.

**Comment by FrozenBurning** [comment]
Exactly. It seems that Google Drive has a strict quota on daily downloads. Therefore, I offer an alternative way to download via Onedrive.

**Comment by FrozenBurning** [comment]
Fixed when switching to One Drive links. Closed
