### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by oldoldcoder** [FrozenBurning/Text2Light#11]
can u tell me what the data set of this algorithm is？
thx

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work. Our data is collected from multiple sources. Please take a look at Section 4 of [our paper](https://arxiv.org/abs/2209.09898) for details.

**Comment by Tangshitao** [comment]
HI, thanks for the amazing work, but I cannot find the training dataset. Is there a way to download the training dataset?

**Comment by FrozenBurning** [comment]
@Tangshitao Thanks for your interest in our work. The training dataset has yet to be released. As our training dataset includes multiple sources whose licenses do not allow us to redistribute, please refer to the Acknowledgment section on our project page (https://frozenburning.github.io/projects/text2light/) for downloading dataset from corresponding sources.

**Comment by FrozenBurning** [comment]
Closed due to inactivity. Feel free to reopen it 🙌
