### ISSUE TITLE
Question about Fig. 2. Spherical Positional Encoding

### ISSUE THREAD

**Issue by sangminkim-99** [FrozenBurning/Text2Light#12]
Hello @FrozenBurning, thank you for sharing your impressive work!

I have read your paper and have a question regarding Figure 2. The spherical positional encoding diagram appears similar to the Integrated Positional Encoding (IPE) suggested by Mip-NeRF. However, I am uncertain about the mean and variance related to the sampling process, as it is not explained in the paper.

Would it be possible for you to kindly provide some explanation regarding the figure, specifically regarding the mean and variance of the sampling process? This would greatly enhance my understanding of your work.

Thank you very much!

![image](https://user-images.githubusercontent.com/65658464/223123967-6e5b3f63-c456-4468-a593-b3b6ff524726.png)

**Comment by FrozenBurning** [comment]
Greetings! Thank you for your interest in our work. We'd like to clarify that the figure you referred to is merely an illustration and does not reflect our use of Integrated Positional Encoding. Rather, we employ vanilla Fourier feature encoding, similar to NeRF, to encode spherical positional coordinates.

**Comment by sangminkim-99** [comment]
Thank you very much for getting back to me, @FrozenBurning.
I appreciate your response and apologize for any confusion caused. Your explanation is helpful in clarifying the encoding method used in your work. I look forward to exploring this paper further. Thank you again for your time and for sharing your work with the community.
