### ISSUE TITLE
Retraining

### ISSUE THREAD

**Issue by taginterco** [FrozenBurning/Text2Light#14]
Where can I retrain the model with my own dataset? And what are the configurations for the model to read the dataset that I can provide

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work. We have provided training details in the [README](https://github.com/FrozenBurning/Text2Light#training). By training our model from scratch, we assume your dataset is stored in a folder containing lots of HDR panoramas (in .hdr/.exr format). Then, you can follow the instruction in [README](https://github.com/FrozenBurning/Text2Light#training) step by step to prepare training data.

**Comment by taginterco** [comment]
do the HDRI panoramas have to be a certain length and width? for example 2048x1024 or just 2:1 ratio @FrozenBurning

**Comment by FrozenBurning** [comment]
Recommend 2:1 ratio as it's the standard format of HDR panoramas. We trained on varied resolutions of HDR panoramas, and the [preprocessing script](https://github.com/FrozenBurning/Text2Light#training) will help you to handle all the things.
