### ISSUE TITLE
Is it possible to do all the training on colab?

### ISSUE THREAD

**Issue by taginterco** [FrozenBurning/Text2Light#15]
I want to train with my own dataset and I preprocessed and everything, but its been tricky doing it all on colab because the trainingstage1.py is using different versions of pytorch lightning, does it have to be only in a conda environment?

**Comment by FrozenBurning** [comment]
I haven't tried to train the model using colab. And I'm afraid that the training would be slow given the limited capacity of GPU. The environment is not necessarily in conda at all. You can install all dependencies via pip according to [environment.yml](https://github.com/FrozenBurning/Text2Light/blob/master/environment.yml).

**Comment by taginterco** [comment]
Thank you!

**Comment by taginterco** [comment]
I tried installing the dependencies manually using pip but the versions sort of conflict with each other, such as there is a module used in pytorch version 1.7 and another one used in pytorch 1.9 but I can only install one of them.
