### ISSUE TITLE
Text descriptions

### ISSUE THREAD

**Issue by zhangfuyang** [FrozenBurning/Text2Light#17]
Hi,

I wonder can you share the text descriptions during the inference stage? So that we can evaluate our method with yours on an apple-to-apple basis

**Comment by FrozenBurning** [comment]
Sure! Check it out in [gdrive](https://drive.google.com/drive/folders/1TtzS28GCbc-iTIAqtgCh_JTSJDoXUGAJ?usp=share_link). The `alt_indoor.txt` is for indoor scenes, and `alt_outdoor.txt` is for outdoor scenes.

**Comment by FrozenBurning** [comment]
Closed. Feel free to reopen it if you have any further issues 👍
