### ISSUE TITLE
Files under taming/data do not exist

### ISSUE THREAD

**Issue by 1211sh** [FrozenBurning/Text2Light#2]
Dear sir,

Hi, I am working on your wonderful work, Text2Light.
I've found out that taming/data directory and files under the directory are not available in your repo.

I've also tried to get the same files from https://github.com/CompVis/taming-transformers, but some functions do not match to your setting (e.g., taming/data/custom.py - CustomTrainHolistic, CustomTestHolistic).

Could you upload the files?
Thanks a lot!

**Comment by FrozenBurning** [comment]
Oops! Thanks for pointing that out. It seems that there is a bug in `.gitignore`. I've fixed it thus all codes under taming/data are uploaded to this repo.

**Comment by 1211sh** [comment]
Thanks!
