### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by caojiehui** [FrozenBurning/Text2Light#21]
"Hello, I am a doctoral student at Zhejiang University, and I am very interested in your research. Can you share your training dataset?"

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! Unfortunately, we cannot redistribute the dataset according to the license. You could refer to our project page (details: https://github.com/FrozenBurning/Text2Light/issues/11#issuecomment-1477331369) for our data source. A majority of them are free to download!

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!
