### ISSUE TITLE
Question about LDR->HDR using SRiTMO

### ISSUE THREAD

**Issue by pureexe** [FrozenBurning/Text2Light#22]
I would like to thank you for creating such a great work.

I am currently working on panorama prediction, and my pipeline currently produces LDR 360 panoramas. I would like to feed the output of my pipeline to the SRiTMO module to get HDR panoramas.

However, when I feed the LDR images from the Laval Indoor Dataset (which is what the paper was trained on) to the SRiTMO module, the output values reach into the millions, while the actual HDR images are not that high. Is this normal? Do you expect this to happen?

This behavior causes the RMSE of the inverse tone-mapping between SRiTMO and the ground truth to reach a range of millions, compared to less than one as reported in the paper (Table 3).

Or I may misunderstand the table. Could you please explain the exact method you used to calculate the RMSE?

You can find the LDR and HDR images from the Laval Indoor Dataset that I used to test here:

https://vistec-my.sharepoint.com/:f:/g/personal/pakkapon_p_s19_vistec_ac_th/EoiQ7nRJZkFDiLQnKIDLVvYBjRF4xKU2shCnfDI1g14zew?e=N1NQtG

Best regards,
Pakkapon Phongthawee

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! The way we calculate RMSE is tailored with scale-invariant preprocessing. Given a paired HDR ground truth and HDR prediction, we load them using this function:
https://github.com/FrozenBurning/Text2Light/blob/ea8eac7e8986df129ccbbd80f38315f54e8f2606/process_hdri.py#L28

Then, we apply tonemapping on HDR ground truth using:
https://github.com/FrozenBurning/Text2Light/blob/ea8eac7e8986df129ccbbd80f38315f54e8f2606/process_hdri.py#L9

Both of the predicted envmap and ground truth envmap are calibrated (https://github.com/FrozenBurning/Text2Light/blob/ea8eac7e8986df129ccbbd80f38315f54e8f2606/process_hdri.py#L85) according to this tonemapped LDR to remove luminance scale. Then the MSE are calculated.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!
