### ISSUE TITLE
How to generate richer images

### ISSUE THREAD

**Issue by potentialming** [FrozenBurning/Text2Light#23]
This is really a great work. I have been very interested in generating panoramic images recently and have also tried your project. But why are the images generated using the same text the same? Is it necessary to set it up somewhere?

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! It depends on two factors: 1) your text description, if the text description is kinda out-of-distribution, the KNN embedding will play an important role during generation; 2) the hyperparameters `temperature` and `top_k` will also control the sampling behavior.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!
