### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by xwg0508** [FrozenBurning/Text2Light#24]
Hello, Thanks for your amazing work! About dataset , i'd like to ask about the  size of pictures in the dataset, 1k,2k,4k or ? For example, Poly-Haven?

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work. Please refer to https://github.com/FrozenBurning/Text2Light/issues/11#issuecomment-1477331369 for details. The resolution of the envmap in the dataset varies from 1K to 4K as we collect from multiple sources. Still, we have the [preprocessing script](https://github.com/FrozenBurning/Text2Light/blob/master/process_hdri.py) for you to handle data preprocessing before training.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!
