### ISSUE TITLE
About global codebook and local codebook

### ISSUE THREAD

**Issue by potentialming** [FrozenBurning/Text2Light#25]
Dear author, your code is very beautiful. Unfortunately, you cannot share your processed data set. However, can you provide the global codebook and local codebook? This will be of great help to us who cannot use the data set directly. Finally, thank you for open sourcing this excellent work.

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! We've released all checkpoints (https://drive.google.com/drive/folders/1HKBjC7oQOzrkGFKMQmSh6PySv6AycDS3) which contain the global codebook and local codebook.

**Comment by potentialming** [comment]
Thanks for clearing up the confusion. I originally thought that all you were given was the checkpoint of the transformer. Thank you very much for your timely reply.

**Comment by FrozenBurning** [comment]
I'm glad your confusion is resolved. Feel free to reopen this issue if you have further questions!
