### ISSUE TITLE
lighting estimation

### ISSUE THREAD

**Issue by Len-Li** [FrozenBurning/Text2Light#3]
Hi, thanks for sharing your great work! 

I am curious that is it possible to do lighting estimation using GAN inversion as in Stylelight?

**Comment by FrozenBurning** [comment]
It is always possible to do the inversion. One naive way is that you can use the encoders of our dual codebook to derive latent representations from input images/patches. And then use that as a condition to sample the full panoramas. Another possible way would be using gradient-based optimization. You may need careful implementation of back-propagation when dealing with the quantization in codebooks.

**Comment by Len-Li** [comment]
> It is always possible to do the inversion. One naive way is that you can use the encoders of our dual codebook to derive latent representations from input images/patches. And then use that as a condition to sample the full panoramas. Another possible way would be using gradient-based optimization. You may need careful implementation of back-propagation when dealing with the quantization in codebooks.

Thanks for your reply. I write a simple script to optimize a latent code, it seems that latent code does not update. Do you have any advice to deal with the quantization in codebooks?

**Comment by FrozenBurning** [comment]
You may refer to some [optimization-based techniques](https://github.com/nerdyrodent/VQGAN-CLIP/blob/main/generate.py) which deal with back-propagation through quantized codebooks.
