### ISSUE TITLE
No HDR export

### ISSUE THREAD

**Issue by maria-sanchez-isaza** [FrozenBurning/Text2Light#4]
Unless I'm missing something it doesn't seem to output HDR images, only PNG. Am I doing something wrong?

**Comment by FrozenBurning** [comment]
Our Colab demo saves EXR images in `./text2light_generated/hdr/`. And if you run the code in the local environment, the output HDRI is saved [here](https://github.com/FrozenBurning/Text2Light/blob/5285b05432dadf19dd4763331c80ba939f34a3c4/text2light.py#L148).
