### ISSUE TITLE
There are problems with the generated HDRIs.

### ISSUE THREAD

**Issue by tdsuper** [FrozenBurning/Text2Light#6]
Dear authors, thanks for this amazing work! 

I tried to generate the HDRIs using the pretrained models and render the balls using these HDRIs. 

However, the rendering results seem to be brighter than yours. One of them is given below.

I don't know whether have I lose some steps, so I raise this issue. 

![hdr_ green grass field with trees and mountains in the distance _balls](https://user-images.githubusercontent.com/213596/203732732-963e86a0-55fe-42fb-86a3-ba68f306fe26.png)

**Comment by FrozenBurning** [comment]
Could you specify the engine you used for rendering this image? It seems that the appearance of renderings is washed out.

**Comment by tdsuper** [comment]
I render the image using the command line script with the same version blender, i.e. blender-3.1.2-linux-x64.

**Comment by FrozenBurning** [comment]
Got it. I've tested by my side. For this scene, you can tune the parameter for SR-iTMO to `boost=5` and `balance=2.7` at [here](https://github.com/FrozenBurning/Text2Light/blob/5285b05432dadf19dd4763331c80ba939f34a3c4/sritmo/global_sritmo.py#L190). There is a scale ambiguity for the range of HDR map, the default parameter works well on most of the scene. These parameters take charge of fine-tuning the rendering quality.

**Comment by tdsuper** [comment]
I have re-generated the HDRI and then re-rendered the balls. The result is much similar to that you provided. Thanks!

But I still have another two questions. The first is whether you use the same parameters for the four rendering results at [here](https://github.com/FrozenBurning/Text2Light#from-command-line). The second question is what is the intuitive meaning of these two parameters. How to adjust them for a given HDRI? Can they be set or adjusted autumatically given hdr_output at [here](https://github.com/FrozenBurning/Text2Light/blob/5285b05432dadf19dd4763331c80ba939f34a3c4/sritmo/global_sritmo.py#L187)?

**Comment by FrozenBurning** [comment]
The intuitive meaning of these parameters is to reduce the scale ambiguity when rendering, which offers another degree of flexibility for users to modify their lighting strength.
