### ISSUE TITLE
Trying to generate 8K hdr images

### ISSUE THREAD

**Issue by Junrongh** [FrozenBurning/Text2Light#7]
Dear author,

Thanks for releasing these fantastic code. I tried to generate a 8K hdr image with your repo but found some issue.
I changed the input
`h=512 w=1024`
into
`h=1024 w=2048`
in this file https://github.com/FrozenBurning/Text2Light/blob/master/text2light.py#L74

The generated holistic image is good, since these parameters will not affect this file.
![holistic_ Sunset California beach](https://user-images.githubusercontent.com/25357711/206956357-104e09e7-db8a-4267-adfa-6de20ea05922.png)
However, the [2048x1024] ldr file has some problem(I resized it manually for uploading)
![ldr_ Sunset California beach](https://user-images.githubusercontent.com/25357711/206956549-b067dd32-3cd9-47e4-913b-123901c746fc.png)

It seems that the spe coordinate should be changed with the input width and height. I'm not so sure what shoud be adjusted. Could you please look into it?

The command line I used is
`python text2light.py -rg logs/global_sampler_clip -rl logs/local_sampler_outdoor --outdir ./generated_panorama --text "Beijing afternoon 4 pm" --clip clip_emb.npy --sritmo ./logs/sritmo.pth --sr_factor 4`

Thank you!

Best wishes

**Comment by FrozenBurning** [comment]
To generate 8K HDR, instead of modifying `h, w`, you need to change the input parameter as `--sr_factor 8`, which directly upscale $512\times1024$ to $4096\times8192$.

**Comment by Junrongh** [comment]
So the model you trained is fixed to 512x1024?
