### ISSUE TITLE
The error of environment

### ISSUE THREAD

**Issue by dlongry** [FrozenBurning/Text2Light#8]
Thanks for releasing this fantastic code.  When I run the code, there is the error as follows:
![image](https://user-images.githubusercontent.com/16435037/212314237-0d08a826-bb33-4574-9330-63a5a72a4c52.png)

Do you know how to solve this problem?  thanks!

**Comment by FrozenBurning** [comment]
You may refer to this [issue](https://github.com/CompVis/latent-diffusion/issues/207).

**Comment by dlongry** [comment]
thanks！ using “pip install packaging==21.3” works for me
