### ISSUE TITLE
The panoramic image generated by the program is very blurry in Blender

### ISSUE THREAD

**Issue by dlongry** [FrozenBurning/Text2Light#9]
Thanks for releasing this outstanding work.  But I find that the panoramic image generated by the program is very blurry in Blender, Even with increasing the sampling rate, there is still no significant improvement. The result shows as follows:
![QQ截图20230115110808](https://user-images.githubusercontent.com/16435037/212521115-d365cae8-c77f-4f54-a377-5b0f29adcea8.png)

is this normal?

**Comment by FrozenBurning** [comment]
This is normal. In Blender, the user perspective only occupies a small region of the entire panorama. Further enhancing the details, e.g., leaves structures in this case, would be an exciting direction.

**Comment by dlongry** [comment]
Thanks for your reply！Looking forward to the next work.
